<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>BlendInteractive.Umbraco.SecurityDashboard</PackageId>
    <Version>1.0.1</Version>
    <Authors>Blend Interactive, Joe Kepley</Authors>
    <Description>The Umbraco Security Dashboard is a package that provides a dashboard within the Umbraco backoffice to help identify potential security vulnerabilities in installed packages. It scans installed packages against known vulnerabilities and can report vulnerabilities to a central location via webhook.</Description>
    <PackageTags>umbraco;security;vulnerability;dashboard;umbraco-marketplace</PackageTags>
    <IsPackable>true</IsPackable>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
    <Title>Umbraco Security Dashboard</Title>
    <PackageProjectUrl>https://github.com/blendinteractive/umbraco-security-dashboard</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/blendinteractive/umbraco-security-dashboard</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Copyright>©2026 Blend Interactive</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
    <None Include="icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms" Version="17.*" />
    <PackageReference Include="NuGet.Versioning" Version="6.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.*" />
  </ItemGroup>


</Project>
